version: "3.8"

services:
  expressmediaserver:
    container_name: expressmediaserver
    build: .
    ports:
      - "8083:8083"
    volumes:
      - /NAS/MediaNet:/media
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: expressmedia-db
    environment:
      POSTGRES_USER=${DB_USER}
      POSTGRES_PASSWORD=${DB_PASS}
      POSTGRES_DB=${DB_NAME}
    volumes:
      - expressmedia_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  expressmedia_db_data:
